# Site
repository: mzoz/modern-resume
# favicon: images/favicon.ico

# Personal info
name: Muye Zhang
title: mobile 0424688800
email: muye.zhang@outlook.com
website: https://mzoz.github.io/modern-resume/

# Social links
# twitter_username: 
github_username:  mzoz
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: muye-zhang-89555bb9
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Muye and I'm an electrical engineering graduate with self-taught programming skills. As well as tuning electronic devices I also have experience making full-stack web apps, with skills particularly in <mark>Java</mark>, <mark>Python</mark> and <mark>FPGA</mark>.

  I'm a permanent resident living in Adelaide, but willing to move to anywhere in Australia for work within the next 24 hours!


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  In my leisure time I enjoy fishing, crabbing and learning new skills.

# Footer
# footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
